var CodeMirrorConfig=window.CodeMirrorConfig||{},CodeMirror=function(){function m(a,b){for(var c in b)a.hasOwnProperty(c)||(a[c]=b[c])}function p(a){return document.createElementNS&&null!==document.documentElement.namespaceURI?document.createElementNS("http://www.w3.org/1999/xhtml",a):document.createElement(a)}function s(a,b){var c=p("div"),f=p("div");c.style.position="absolute";c.style.height="100%";if(c.style.setExpression)try{c.style.setExpression("height","this.previousSibling.offsetHeight + 'px'")}catch(g){}c.style.top=
"0px";c.style.left="0px";c.style.overflow="hidden";a.appendChild(c);f.className="CodeMirror-line-numbers";c.appendChild(f);f.innerHTML="<div>"+b+"</div>";return c}function u(a){"string"==typeof a.parserfile&&(a.parserfile=[a.parserfile]);"string"==typeof a.basefiles&&(a.basefiles=[a.basefiles]);"string"==typeof a.stylesheet&&(a.stylesheet=[a.stylesheet]);var b=' spellcheck="'+(a.disableSpellcheck?"false":"true")+'"',c=['<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html'+
b+"><head>"];c.push('<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>');for(var f=a.noScriptCaching?"?nocache="+(new Date).getTime().toString(16):"",g=a.stylesheet,e=0;e<g.length;e++)c.push('<link rel="stylesheet" type="text/css" href="'+g[e]+f+'"/>');g=a.basefiles.concat(a.parserfile);for(e=0;e<g.length;e++){var d=g[e];/^https?:/.test(d)||(d=a.path+d);c.push('<script type="text/javascript" src="'+d+f+'">\x3c/script>')}c.push('</head><body style="border-width: 0;" class="editbox"'+b+"></body></html>");
return c.join("")}function j(a,b){this.options=b=b||{};m(b,CodeMirrorConfig);b.dumbTabs?b.tabMode="spaces":b.normalTab&&(b.tabMode="default");b.cursorActivity&&(b.onCursorActivity=b.cursorActivity);var c=this.frame=p("iframe");b.iframeClass&&(c.className=b.iframeClass);b.iframeId&&(c.id=b.iframeId);c.frameBorder=0;c.style.border="0";c.style.width="100%";c.style.height="100%";c.style.display="block";var f=this.wrapping=p("div");f.style.position="relative";f.className="CodeMirror-wrapping";f.style.width=
b.width;f.style.height="dynamic"==b.height?b.minHeight+"px":b.height;var g=this.textareaHack=p("textarea");f.appendChild(g);g.style.position="absolute";g.style.left="-10000px";g.style.width="10px";g.tabIndex=1E5;c.CodeMirror=this;b.domain&&v?(this.html=u(b),c.src="javascript:(function(){document.open();"+(b.domain?'document.domain="'+b.domain+'";':"")+"document.write(window.frameElement.CodeMirror.html);document.close();})()"):c.src="javascript:;";a.appendChild?a.appendChild(f):a(f);f.appendChild(c);
b.lineNumbers&&(this.lineNumbers=s(f,b.firstLineNumber));this.win=c.contentWindow;if(!b.domain||!v)this.win.document.open(),this.win.document.write(u(b)),this.win.document.close()}m(CodeMirrorConfig,{stylesheet:[],path:"",parserfile:[],basefiles:"util.js stringstream.js select.js undo.js editor.js tokenize.js".split(" "),iframeId:null,iframeClass:null,passDelay:200,passTime:50,lineNumberDelay:200,lineNumberTime:50,continuousScanning:!1,saveFunction:null,onLoad:null,onChange:null,undoDepth:50,undoDelay:800,
disableSpellcheck:!0,textWrapping:!0,readOnly:!1,width:"",height:"300px",minHeight:100,autoMatchParens:!1,markParen:null,unmarkParen:null,parserConfig:null,tabMode:"indent",enterMode:"indent",electricChars:!0,reindentOnLoad:!1,activeTokens:null,onCursorActivity:null,lineNumbers:!1,firstLineNumber:1,onLineNumberClick:null,indentUnit:2,domain:null,noScriptCaching:!1,incrementalLoading:!1});var v=document.selection&&window.ActiveXObject&&/MSIE/.test(navigator.userAgent);j.prototype={init:function(){this.options.initCallback&&
this.options.initCallback(this);if(this.options.onLoad)this.options.onLoad(this);this.options.lineNumbers&&this.activateLineNumbers();this.options.reindentOnLoad&&this.reindent();"dynamic"==this.options.height&&this.setDynamicHeight()},getCode:function(){return this.editor.getCode()},setCode:function(a){this.editor.importCode(a)},canHighlight:function(){return!0},highlightSql:function(a,b,c){return this.win.highlightSql(a,b,c)},getSelection:function(){this.focusIfIE();return this.editor.selectedText()},
reindent:function(){this.editor.reindent()},reindentSelection:function(){this.focusIfIE();this.editor.reindentSelection(null)},focusIfIE:function(){this.win.select.ie_selection&&document.activeElement!=this.frame&&this.focus()},focus:function(){this.win.focus();this.editor.selectionSnapshot&&this.win.select.setBookmark(this.win.document.body,this.editor.selectionSnapshot)},replaceSelection:function(a){this.focus();this.editor.replaceSelection(a);return!0},replaceChars:function(a,b,c){this.editor.replaceChars(a,
b,c)},getSearchCursor:function(a,b,c){return this.editor.getSearchCursor(a,b,c)},undo:function(){this.editor.history.undo()},redo:function(){this.editor.history.redo()},historySize:function(){return this.editor.history.historySize()},clearHistory:function(){this.editor.history.clear()},grabKeys:function(a,b){this.editor.grabKeys(a,b)},ungrabKeys:function(){this.editor.ungrabKeys()},setParser:function(a,b){this.editor.setParser(a,b)},setSpellcheck:function(a){this.win.document.body.spellcheck=a},setStylesheet:function(a){"string"===
typeof a&&(a=[a]);for(var b={},c={},f=this.win.document.getElementsByTagName("link"),g=0,e;e=f[g];g++)if(-1!==e.rel.indexOf("stylesheet"))for(var d=0;d<a.length;d++){var h=a[d];e.href.substring(e.href.length-h.length)===h&&(b[e.href]=!0,c[h]=!0)}for(g=0;e=f[g];g++)-1!==e.rel.indexOf("stylesheet")&&(e.disabled=!(e.href in b));for(d=0;d<a.length;d++)h=a[d],h in c||(e=this.win.document.createElement("link"),e.rel="stylesheet",e.type="text/css",e.href=h,this.win.document.getElementsByTagName("head")[0].appendChild(e))},
setTextWrapping:function(a){a!=this.options.textWrapping&&(this.win.document.body.style.whiteSpace=a?"":"nowrap",this.options.textWrapping=a,this.lineNumbers&&(this.setLineNumbers(!1),this.setLineNumbers(!0)))},setIndentUnit:function(a){this.win.indentUnit=a},setUndoDepth:function(a){this.editor.history.maxDepth=a},setTabMode:function(a){this.options.tabMode=a},setEnterMode:function(a){this.options.enterMode=a},setLineNumbers:function(a){a&&!this.lineNumbers?(this.lineNumbers=s(this.wrapping,this.options.firstLineNumber),
this.activateLineNumbers()):!a&&this.lineNumbers&&(this.wrapping.removeChild(this.lineNumbers),this.wrapping.style.paddingLeft="",this.lineNumbers=null)},cursorPosition:function(a){this.focusIfIE();return this.editor.cursorPosition(a)},firstLine:function(){return this.editor.firstLine()},lastLine:function(){return this.editor.lastLine()},nextLine:function(a){return this.editor.nextLine(a)},prevLine:function(a){return this.editor.prevLine(a)},lineContent:function(a){return this.editor.lineContent(a)},
setLineContent:function(a,b){this.editor.setLineContent(a,b)},removeLine:function(a){this.editor.removeLine(a)},insertIntoLine:function(a,b,c){this.editor.insertIntoLine(a,b,c)},selectLines:function(a,b,c,f){this.win.focus();this.editor.selectLines(a,b,c,f)},nthLine:function(a){for(var b=this.firstLine();1<a&&!1!==b;a--)b=this.nextLine(b);return b},lineNumber:function(a){for(var b=0;!1!==a;)b++,a=this.prevLine(a);return b},jumpToLine:function(a){"number"==typeof a&&(a=this.nthLine(a));this.selectLines(a,
0);this.win.focus()},currentLine:function(){return this.lineNumber(this.cursorLine())},cursorLine:function(){return this.cursorPosition().line},cursorCoords:function(a){return this.editor.cursorCoords(a)},activateLineNumbers:function(){function a(){if(0!=e.offsetWidth){for(var a=e;a.parentNode;a=a.parentNode);if(!k.parentNode||a!=document||!d.Editor){try{x()}catch(b){}clearInterval(m)}else k.offsetWidth!=j&&(j=k.offsetWidth,e.parentNode.style.paddingLeft=j+"px")}}function b(){k.scrollTop=w.scrollTop||
h.documentElement.scrollTop||0}function c(a){var b=n.firstChild.offsetHeight;if(0!=b)for(var c=50+Math.max(w.offsetHeight,Math.max(e.offsetHeight,w.scrollHeight||0)),b=Math.ceil(c/b),c=n.childNodes.length;c<=b;c++){var d=p("div");d.appendChild(document.createTextNode(a?String(c+l.options.firstLineNumber):"\u00a0"));n.appendChild(d)}}function f(){function a(){c(!0);b()}l.updateNumbers=a;var e=d.addEventHandler(d,"scroll",b,!0),f=d.addEventHandler(d,"resize",a,!0);x=function(){e();f();l.updateNumbers==
a&&(l.updateNumbers=null)};a()}function g(){function a(b,c){j||(j=n.appendChild(p("div")));s&&s(j,c,b);q.push(j);q.push(b);t=j.offsetHeight+j.offsetTop;j=j.nextSibling}function e(){for(var a=0;a<q.length;a+=2)q[a].innerHTML=q[a+1];q=[]}function f(){if(n.parentNode&&n.parentNode==l.lineNumbers){for(var c=(new Date).getTime()+l.options.lineNumberTime;h;){for(a(m++,h.previousSibling);h&&!d.isBR(h);h=h.nextSibling)for(var g=h.offsetTop+h.offsetHeight;n.offsetHeight&&g-3>t;){var k=t;a("&nbsp;");if(t<=
k)break}h&&(h=h.nextSibling);if((new Date).getTime()>c){e();r=setTimeout(f,l.options.lineNumberDelay);return}}for(;j;)a(m++);e();b()}}function g(a){b();c(a);h=w.firstChild;j=n.firstChild;t=0;m=l.options.firstLineNumber;f()}function k(){r&&clearTimeout(r);l.editor.allClean()?g():r=setTimeout(k,200)}var h,j,m,t,q=[],s=l.options.styleNumbers;g(!0);var r=null;l.updateNumbers=k;var u=d.addEventHandler(d,"scroll",b,!0),v=d.addEventHandler(d,"resize",k,!0);x=function(){r&&clearTimeout(r);l.updateNumbers==
k&&(l.updateNumbers=null);u();v()}}var e=this.frame,d=e.contentWindow,h=d.document,w=h.body,k=this.lineNumbers,n=k.firstChild,l=this,j=null;k.onclick=function(a){var b=l.options.onLineNumberClick;if(b){a=(a||window.event).target||(a||window.event).srcElement;var c=a==k?NaN:Number(a.innerHTML);isNaN(c)||b(c,a)}};var x=function(){};a();var m=setInterval(a,500);(this.options.textWrapping||this.options.styleNumbers?g:f)()},setDynamicHeight:function(){function a(){for(var a=0,c=g.lastChild,d;c&&f.isBR(c);)c.hackBR||
a++,c=c.previousSibling;c?(e=c.offsetHeight,d=c.offsetTop+(1+a)*e):e&&(d=a*e);d&&(b.wrapping.style.height=Math.max(h+d,b.options.minHeight)+"px")}var b=this,c=b.options.onCursorActivity,f=b.win,g=f.document.body,e=null,d=null,h=2*b.frame.offsetTop;g.style.overflowY="hidden";f.document.documentElement.style.overflowY="hidden";this.frame.scrolling="no";setTimeout(a,300);b.options.onCursorActivity=function(b){c&&c(b);clearTimeout(d);d=setTimeout(a,100)}}};j.InvalidLineHandle={toString:function(){return"CodeMirror.InvalidLineHandle"}};
j.replace=function(a){"string"==typeof a&&(a=document.getElementById(a));return function(b){a.parentNode.replaceChild(b,a)}};j.fromTextArea=function(a,b){function c(){a.value=d.getCode()}"string"==typeof a&&(a=document.getElementById(a));b=b||{};a.style.width&&null==b.width&&(b.width=a.style.width);a.style.height&&null==b.height&&(b.height=a.style.height);null==b.content&&(b.content=a.value);if(a.form){"function"==typeof a.form.addEventListener?a.form.addEventListener("submit",c,!1):a.form.attachEvent("onsubmit",
c);var f=a.form.submit,g=function(){c();a.form.submit=f;a.form.submit();a.form.submit=g};try{a.form.submit=g}catch(e){}}a.style.display="none";var d=new j(function(b){a.nextSibling?a.parentNode.insertBefore(b,a.nextSibling):a.parentNode.appendChild(b)},b);d.save=c;d.toTextArea=function(){c();a.parentNode.removeChild(d.wrapping);a.style.display="";if(a.form){try{a.form.submit=f}catch(b){}"function"==typeof a.form.removeEventListener?a.form.removeEventListener("submit",c,!1):a.form.detachEvent("onsubmit",
c)}};return d};j.isProbablySupported=function(){var a;return window.opera?9.52<=Number(window.opera.version()):/Apple Computer, Inc/.test(navigator.vendor)&&(a=navigator.userAgent.match(/Version\/(\d+(?:\.\d+)?)\./))?3<=Number(a[1]):document.selection&&window.ActiveXObject&&(a=navigator.userAgent.match(/MSIE (\d+(?:\.\d*)?)\b/))?6<=Number(a[1]):(a=navigator.userAgent.match(/gecko\/(\d{8})/i))?20050901<=Number(a[1]):(a=navigator.userAgent.match(/AppleWebKit\/(\d+)/))?525<=Number(a[1]):null};return j}();
