(function(b){var e={maximize:!1,minimize:!1,dblclick:!1,titlebar:!1,icons:{maximize:"ui-icon-extlink",minimize:"ui-icon-minus",restore:"ui-icon-newwin"},events:{load:null,beforeCollapse:null,beforeMaximize:null,beforeMinimize:null,beforeRestore:null,collapse:null,maximize:null,minimize:null,restore:null}},c,f={init:function(a){b(this).dialog||b.error("jQuery.dialogExtend Error : Only jQuery UI Dialog element is accepted");a=a||{};a.icons=a.icons||{};a.events=a.events||{};c=b.extend({},e,a);c.icons=
b.extend({},e.icons,a.icons);c.events=b.extend({},e.events,a.events);b(this).each(function(){b(this).data("dialog-state","normal").dialogExtend("_verifySettings").dialogExtend("_initEvents").dialogExtend("_initStyles").dialogExtend("_initButtons").dialogExtend("_initTitleBar").dialogExtend("_trigger","load")});return this},collapse:function(){var a=b(this).dialog("widget").find(".ui-dialog-titlebar").height()+15;b(this).dialogExtend("_trigger","beforeCollapse").dialogExtend("_saveSnapshot").data("dialog-state",
"collapsed").dialog("option",{height:a,maxHeight:a}).hide().dialog("widget").find(".ui-dialog-buttonpane:visible").hide().end().find(".ui-dialog-titlebar").css("white-space","nowrap").end().find(".ui-dialog-content").dialogExtend("_trigger","collapse");return this},maximize:function(){var a=b(window).height()-11,c=b(window).width()-11;b(this).dialogExtend("_trigger","beforeMaximize").dialogExtend("_saveSnapshot").data("dialog-state","maximized").dialogExtend("_toggleButtons").dialog("widget").css("position",
"fixed").find(".ui-dialog-content").show().dialog("widget").find(".ui-dialog-buttonpane").show().end().find(".ui-dialog-content").dialog("option",{resizable:!1,draggable:!1,height:a,width:c,position:[1,1]}).dialog("widget").draggable("option","handle",null).find(".ui-dialog-draggable-handle").css("cursor","text").end().find(".ui-dialog-content").dialogExtend("_trigger","maximize");return this},minimize:function(){b(this).dialogExtend("_trigger","beforeMinimize").dialogExtend("_saveSnapshot").data("dialog-state",
"minimized").dialogExtend("_toggleButtons").dialog("widget").hide().find(".ui-dialog-content").dialogExtend("_trigger","minimize");return this},restore:function(){var a=b(this).data("dialog-state");b(this).dialogExtend("_trigger","beforeRestore").data("dialog-state","normal").dialogExtend("_toggleButtons").dialogExtend("maximized"==a?"_restoreFromMaximized":"minimized"==a?"_restoreFromMinimized":"collapsed"==a?"_restoreFromCollapsed":b.error("jQuery.dialogExtend Error : Cannot restore dialog from unknown state '"+
a+"'")).dialog("widget").show().dialogExtend("_trigger","restore");return this},_initButtons:function(){var a=this,d=b(a).dialog("widget").find(".ui-dialog-titlebar");b(d).append('<a class="ui-dialog-titlebar-maximize ui-corner-all" href="#"><span class="ui-icon '+c.icons.maximize+'">maximize</span></a>').append('<a class="ui-dialog-titlebar-minimize ui-corner-all" href="#"><span class="ui-icon '+c.icons.minimize+'">minimize</span></a>').append('<a class="ui-dialog-titlebar-restore ui-corner-all" href="#"><span class="ui-icon '+
c.icons.restore+'">restore</span></a>').find(".ui-dialog-titlebar-maximize,.ui-dialog-titlebar-minimize,.ui-dialog-titlebar-restore").attr("role","button").mouseover(function(){b(this).addClass("ui-state-hover")}).mouseout(function(){b(this).removeClass("ui-state-hover")}).focus(function(){b(this).addClass("ui-state-focus")}).blur(function(){b(this).removeClass("ui-state-focus")}).end().find(".ui-dialog-titlebar-maximize").toggle(c.maximize).css({right:c.maximize?"1.4em":"-9999em"}).click(function(c){c.preventDefault();
b(a).dialogExtend("maximize")}).end().find(".ui-dialog-titlebar-minimize").toggle(c.minimize).css({right:c.maximize?"2.5em":c.minimize?"1.4em":"-9999em"}).click(function(c){c.preventDefault();b(a).dialogExtend("minimize")}).end().find(".ui-dialog-titlebar-restore").hide().css({right:"-9999em"}).click(function(c){c.preventDefault();b(a).dialogExtend("restore")}).end().dblclick(function(d){c.dblclick&&c.dblclick.length&&b(a).dialogExtend("normal"!=b(a).data("dialog-state")?"restore":c.dblclick)}).each(function(){b(this).select(function(){return!1})});
return a},_initEvents:function(){var a=this;b.each(c.events,function(d){b.isFunction(c.events[d])&&b(a).bind(d+".dialogExtend",c.events[d])});return a},_initStyles:function(){var a;a='<style type="text/css">.ui-dialog .ui-dialog-titlebar-maximize,';a+=".ui-dialog .ui-dialog-titlebar-minimize,";a+=".ui-dialog .ui-dialog-titlebar-restore { position: absolute; top: 50%; width: 19px; margin: -10px 8px 0 0; padding: 1px; height: 18px; }";a+=".ui-dialog .ui-dialog-titlebar-maximize span,";a+=".ui-dialog .ui-dialog-titlebar-minimize span,";
a+=".ui-dialog .ui-dialog-titlebar-restore span { display: block; margin: 1px; }";a+=".ui-dialog .ui-dialog-titlebar-maximize:hover,";a+=".ui-dialog .ui-dialog-titlebar-maximize:focus,";a+=".ui-dialog .ui-dialog-titlebar-minimize:hover,";a+=".ui-dialog .ui-dialog-titlebar-minimize:focus,";a+=".ui-dialog .ui-dialog-titlebar-restore:hover,";a+=".ui-dialog .ui-dialog-titlebar-restore:focus { padding: 0; }";a+=".ui-dialog .ui-dialog-titlebar ::selection { background-color: transparent; }";a+="</style>";
b(a).appendTo("body");return this},_initTitleBar:function(){switch(c.titlebar){case !1:break;case "none":if(b(this).dialog("option","draggable")){var a=b("<div />").addClass("ui-dialog-draggable-handle").css("cursor","move").height(5);b(this).dialog("widget").prepend(a).draggable("option","handle",a)}b(this).dialog("widget").find(".ui-dialog-titlebar").find(".ui-dialog-title").html("&nbsp;").end().css({"background-color":"transparent","background-image":"none",border:0,position:"absolute",right:0,
top:0,"z-index":9999}).end();break;case "transparent":b(this).dialog("widget").find(".ui-dialog-titlebar").css({"background-color":"transparent","background-image":"none",border:0});break;default:b.error("jQuery.dialogExtend Error : Invalid <titlebar> value '"+c.titlebar+"'")}return this},_loadSnapshot:function(){return{config:{resizable:b(this).data("original-config-resizable"),draggable:b(this).data("original-config-draggable")},size:{height:b(this).data("original-size-height"),width:b(this).data("original-size-width"),
maxHeight:b(this).data("original-size-maxHeight")},position:{mode:b(this).data("original-position-mode"),left:b(this).data("original-position-left"),top:b(this).data("original-position-top")},titlebar:{wrap:b(this).data("original-titlebar-wrap")}}},_restoreFromCollapsed:function(){var a=b(this).dialogExtend("_loadSnapshot");b(this).show().dialog("widget").find(".ui-dialog-buttonpane:hidden").show().end().find(".ui-dialog-titlebar").css("white-space",a.titlebar.wrap).end().find(".ui-dialog-content").dialog("option",
{height:a.size.height,maxHeight:a.size.maxHeight});return this},_restoreFromMaximized:function(){var a=b(this).dialogExtend("_loadSnapshot");b(this).dialog("widget").css("position",a.position.mode).find(".ui-dialog-titlebar").css("white-space",a.titlebar.wrap).end().find(".ui-dialog-content").dialog("option",{resizable:a.config.resizable,draggable:a.config.draggable,height:a.size.height,width:a.size.width,maxHeight:a.size.maxHeight,position:[a.position.left,a.position.top]}).dialog("widget").draggable("option",
"handle",b(this).find(".ui-dialog-draggable-handle")).find(".ui-dialog-draggable-handle").css("cursor","move");return this},_restoreFromMinimized:function(){b(this).dialogExtend("_loadSnapshot");b(this).dialog("widget").find(".ui-dialog-content").dialog("widget").draggable("option","handle",b(this).find(".ui-dialog-draggable-handle")).find(".ui-dialog-draggable-handle").css("cursor","move");return this},_saveSnapshot:function(){"normal"==b(this).data("dialog-state")&&b(this).data("original-config-resizable",
b(this).dialog("option","resizable")).data("original-config-draggable",b(this).dialog("option","draggable")).data("original-size-height",b(this).dialog("widget").height()).data("original-size-width",b(this).dialog("option","width")).data("original-size-maxHeight",b(this).dialog("option","maxHeight")).data("original-position-mode",b(this).dialog("widget").css("position")).data("original-position-left",b(this).dialog("widget").offset().left).data("original-position-top",b(this).dialog("widget").offset().top).data("original-titlebar-wrap",
b(this).dialog("widget").find(".ui-dialog-titlebar").css("white-space"));return this},_toggleButtons:function(){b(this).dialog("widget").find(".ui-dialog-titlebar-maximize").toggle("maximized"!=b(this).data("dialog-state")&&c.maximize).end().find(".ui-dialog-titlebar-minimize").toggle("minimized"!=b(this).data("dialog-state")&&c.minimize).end().find(".ui-dialog-titlebar-restore").toggle("normal"!=b(this).data("dialog-state")&&(c.maximize||c.minimize)).css({right:"maximized"==b(this).data("dialog-state")?
"24px":"minimized"==b(this).data("dialog-state")?c.maximize?"48px":"24px":"-9999em"}).end();return this},_trigger:function(a){b(this).triggerHandler(a+".dialogExtend",this);return this},_verifySettings:function(){c.dblclick&&"maximize"!=c.dblclick&&"minimize"!=c.dblclick&&"collapse"!=c.dblclick&&(b.error("jQuery.dialogExtend Error : Invalid <dblclick> value '"+c.dblclick+"'"),c.dblclick=!1);c.titlebar&&"none"!=c.titlebar&&"transparent"!=c.titlebar&&(b.error("jQuery.dialogExtend Error : Invalid <titlebar> value '"+
c.titlebar+"'"),c.titlebar=!1);return this}};b.fn.dialogExtend=function(a){if(f[a])return f[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"!==typeof a&&a)b.error("jQuery.dialogExtend Error : Method <"+a+"> does not exist");else return f.init.apply(this,arguments)}})(jQuery);
