/*
 jquery.layout 1.3.0 - Release Candidate 29.8
 $Date: 2010-09-27 08:00:00 (Mon, 27 Sep 2010) $
 $Rev: 30298 $

 Copyright (c) 2010 
   Fabrizio Balliano (http://www.fabrizioballiano.net)
   Kevin Dalman (http://allpro.net)

 Dual licensed under the GPL (http://www.gnu.org/licenses/gpl.html)
 and MIT (http://www.opensource.org/licenses/mit-license.php) licenses.

 Docs: http://layout.jquery-dev.net/documentation.html
 Tips: http://layout.jquery-dev.net/tips.html
 Help: http://groups.google.com/group/jquery-ui-layout
*/
(function(f){var v=f.browser;f.layout={browser:{mozilla:v.mozilla,webkit:v.webkit||v.safari||!1,msie:v.msie,isIE6:v.msie&&6==v.version,boxModel:!1},scrollbarWidth:function(){return window.scrollbarWidth||f.layout.getScrollbarSize("width")},scrollbarHeight:function(){return window.scrollbarHeight||f.layout.getScrollbarSize("height")},getScrollbarSize:function(h){var p=f('<div style="position: absolute; top: -10000px; left: -10000px; width: 100px; height: 100px; overflow: scroll;"></div>').appendTo("body"),
q={width:p.width()-p[0].clientWidth,height:p.height()-p[0].clientHeight};p.remove();window.scrollbarWidth=q.width;window.scrollbarHeight=q.height;return h.match(/^(width|height)$/i)?q[h]:q},showInvisibly:function(h,p){if(!h)return{};h.jquery||(h=f(h));var q={display:h.css("display"),visibility:h.css("visibility")};return p||"none"==q.display?(h.css({display:"block",visibility:"hidden"}),q):{}},getElemDims:function(h){var p={},q=p.css={},r={},K,v,x=h.offset();p.offsetLeft=x.left;p.offsetTop=x.top;
f.each(["Left","Right","Top","Bottom"],function(y,x){K=q["border"+x]=f.layout.borderWidth(h,x);v=q["padding"+x]=f.layout.cssNum(h,"padding"+x);r[x]=K+v;p["inset"+x]=v});p.offsetWidth=h.innerWidth();p.offsetHeight=h.innerHeight();p.outerWidth=h.outerWidth();p.outerHeight=h.outerHeight();p.innerWidth=p.outerWidth-r.Left-r.Right;p.innerHeight=p.outerHeight-r.Top-r.Bottom;q.width=h.width();q.height=h.height();return p},getElemCSS:function(f,p){var q={},r=f[0].style,v=p.split(","),M=["Top","Bottom","Left",
"Right"],x=["Color","Style","Width"],y,L,Q,V,W,da;for(V=0;V<v.length;V++)if(y=v[V],y.match(/(border|padding|margin)$/))for(W=0;4>W;W++)if(L=M[W],"border"==y)for(da=0;3>da;da++)Q=x[da],q[y+L+Q]=r[y+L+Q];else q[y+L]=r[y+L];else q[y]=r[y];return q},cssWidth:function(h,p){var q=f.layout.borderWidth,r=f.layout.cssNum;if(0>=p)return 0;if(!f.layout.browser.boxModel)return p;q=p-q(h,"Left")-q(h,"Right")-r(h,"paddingLeft")-r(h,"paddingRight");return 0<q?q:0},cssHeight:function(h,p){var q=f.layout.borderWidth,
r=f.layout.cssNum;if(0>=p)return 0;if(!f.layout.browser.boxModel)return p;q=p-q(h,"Top")-q(h,"Bottom")-r(h,"paddingTop")-r(h,"paddingBottom");return 0<q?q:0},cssNum:function(h,p){h.jquery||(h=f(h));var q=f.layout.showInvisibly(h),r=parseInt(f.curCSS(h[0],p,!0),10)||0;h.css(q);return r},borderWidth:function(h,p){h.jquery&&(h=h[0]);var q="border"+p.substr(0,1).toUpperCase()+p.substr(1);return"none"==f.curCSS(h,q+"Style",!0)?0:parseInt(f.curCSS(h,q+"Width",!0),10)||0}};f.fn.layout=function(h){function p(a){if(!a)return!0;
var b=a.keyCode;if(33>b)return!0;var c={38:"north",40:"south",37:"west",39:"east"},e=a.shiftKey,d=a.ctrlKey,t,g,j,l;d&&(37<=b&&40>=b)&&n[c[b]].enableCursorHotkey?l=c[b]:(d||e)&&f.each(k.borderPanes.split(","),function(a,c){t=n[c];g=t.customHotkey;j=t.customHotkeyModifier;if(e&&"SHIFT"==j||d&&"CTRL"==j||d&&e)if(g&&b==(isNaN(g)||9>=g?g.toUpperCase().charCodeAt(0):g))return l=c,!1});if(!l||!u[l]||!n[l].closable||m[l].isHidden)return!0;ia(l);a.stopPropagation();return a.returnValue=!1}function q(a){this&&
this.tagName&&(a=this);var b;N(a)?b=u[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),!1});if(b&&b.length){var c=b.data("layoutEdge");a=m[c];a.cssSaved&&r(c);if(a.isSliding||a.isResizing||a.isClosed)a.cssSaved=!1;else{var e={zIndex:k.zIndex.pane_normal+2},d={},t=b.css("overflow"),g=b.css("overflowX"),j=b.css("overflowY");"visible"!=t&&(d.overflow=t,e.overflow="visible");g&&!g.match(/visible|auto/)&&(d.overflowX=g,e.overflowX="visible");
j&&!j.match(/visible|auto/)&&(d.overflowY=g,e.overflowY="visible");a.cssSaved=d;b.css(e);f.each(k.allPanes.split(","),function(a,b){b!=c&&r(b)})}}}function r(a){this&&this.tagName&&(a=this);var b;N(a)?b=u[a]:f(a).data("layoutRole")?b=f(a):f(a).parents().each(function(){if(f(this).data("layoutRole"))return b=f(this),!1});if(b&&b.length){a=b.data("layoutEdge");a=m[a];var c=a.cssSaved||{};!a.isSliding&&!a.isResizing&&b.css("zIndex",k.zIndex.pane_normal);b.css(c);a.cssSaved=!1}}function v(a,b,c){var e=
f(a);if(e.length)if(-1==k.borderPanes.indexOf(b))alert(G.errButton+G.Pane.toLowerCase()+": "+b);else return a=n[b].buttonClass+"-"+c,e.addClass(a+" "+a+"-"+b).data("layoutName",n.name),e;else alert(G.errButton+G.selector+": "+a);return null}function M(a,b,c){switch(b.toLowerCase()){case "toggle":x(a,c);break;case "open":y(a,c);break;case "close":L(a,c);break;case "pin":Q(a,c);break;case "toggle-slide":x(a,c,!0);break;case "open-slide":y(a,c,!0)}}function x(a,b,c){(a=v(a,b,"toggle"))&&a.click(function(a){ia(b,
!!c);a.stopPropagation()})}function y(a,b,c){(a=v(a,b,"open"))&&a.attr("title",G.Open).click(function(a){X(b,!!c);a.stopPropagation()})}function L(a,b){var c=v(a,b,"close");c&&c.attr("title",G.Close).click(function(a){R(b);a.stopPropagation()})}function Q(a,b){var c=v(a,b,"pin");if(c){var e=m[b];c.click(function(a){W(f(this),b,e.isSliding||e.isClosed);e.isSliding||e.isClosed?X(b):R(b);a.stopPropagation()});W(c,b,!e.isClosed&&!e.isSliding);k[b].pins.push(a)}}function V(a,b){f.each(k[a].pins,function(c,
e){W(f(e),a,b)})}function W(a,b,c){var e=a.attr("pin");if(!(e&&c==("down"==e))){var e=n[b].buttonClass+"-pin",d=e+"-"+b;b=e+"-up "+d+"-up";e=e+"-down "+d+"-down";a.attr("pin",c?"down":"up").attr("title",c?G.Unpin:G.Pin).removeClass(c?b:e).addClass(c?e:b)}}function da(a){a=f.extend({},n.cookie,a||{}).name||n.name||"Layout";for(var b=document.cookie,b=b?b.split(";"):[],c,e=0,d=b.length;e<d;e++)if(c=f.trim(b[e]).split("="),c[0]==a)return Ka(decodeURIComponent(c[1]));return""}function za(a,b){var c=f.extend({},
n.cookie,b||{}),e=c.name||n.name||"Layout",d="",t="",g=!1;c.expires.toUTCString?t=c.expires:"number"==typeof c.expires&&(t=new Date,0<c.expires?t.setDate(t.getDate()+c.expires):(t.setYear(1970),g=!0));t&&(d+=";expires="+t.toUTCString());c.path&&(d+=";path="+c.path);c.domain&&(d+=";domain="+c.domain);c.secure&&(d+=";secure");g?(m.cookie={},document.cookie=e+"="+d):(m.cookie=Aa(a||c.keys),document.cookie=e+"="+encodeURIComponent(La(m.cookie))+d);return f.extend({},m.cookie)}function Ma(a){if(a=da(a))m.cookie=
f.extend({},a),Na(a);return a}function Na(a){f.extend(!0,n,a)}function Aa(a){var b={},c={isClosed:"initClosed",isHidden:"initHidden"},e,d,t;a||(a=n.cookie.keys);f.isArray(a)&&(a=a.join(","));a=a.replace(/__/g,".").split(",");for(var g=0,j=a.length;g<j;g++)e=a[g].split("."),d=e[0],e=e[1],0>k.allPanes.indexOf(d)||(t=m[d][e],void 0!=t&&("isClosed"==e&&m[d].isSliding&&(t=!0),(b[d]||(b[d]={}))[c[e]?c[e]:e]=t));return b}function La(a){function b(a){var e=[],d=0,f,g,j;for(f in a)g=a[f],j=typeof g,"string"==
j?g='"'+g+'"':"object"==j&&(g=b(g)),e[d++]='"'+f+'":'+g;return"{"+e.join(",")+"}"}return b(a)}function Ka(a){try{return window.eval("("+a+")")||{}}catch(b){return{}}}var G={Pane:__("Pane"),Open:__("Open"),Close:__("Close"),Resize:__("Resize"),Slide:__("Slide Open"),Pin:__("Pin"),Unpin:__("Un-Pin"),selector:__("selector"),msgNoRoom:__("Not enough room to show this pane."),errContainerMissing:"UI Layout Initialization Error\n\nThe specified layout-container does not exist.",errCenterPaneMissing:"UI Layout Initialization Error\n\nThe center-pane element does not exist.\n\nThe center-pane is a required element.",
errContainerHeight:"UI Layout Initialization Warning\n\nThe layout-container \"CONTAINER\" has no height.\n\nTherefore the layout is 0-height and hence 'invisible'!",errButton:"Error Adding Button \n\nInvalid "},n={name:"",scrollToBookmarkOnLoad:!0,resizeWithWindow:!0,resizeWithWindowDelay:200,resizeWithWindowMaxDelay:0,onresizeall_start:null,onresizeall_end:null,onload:null,onunload:null,autoBindCustomButtons:!1,zIndex:null,defaults:{applyDemoStyles:!1,closable:!0,resizable:!0,slidable:!0,initClosed:!1,
initHidden:!1,contentSelector:".ui-layout-content",contentIgnoreSelector:".ui-layout-ignore",findNestedContent:!1,paneClass:"ui-layout-pane",resizerClass:"ui-layout-resizer",togglerClass:"ui-layout-toggler",buttonClass:"ui-layout-button",minSize:0,maxSize:0,spacing_open:6,spacing_closed:6,togglerLength_open:50,togglerLength_closed:50,togglerAlign_open:"center",togglerAlign_closed:"center",togglerTip_open:G.Close,togglerTip_closed:G.Open,togglerContent_open:"",togglerContent_closed:"",resizerDblClickToggle:!0,
autoResize:!0,autoReopen:!0,resizerDragOpacity:1,maskIframesOnResize:!0,resizeNestedLayout:!0,resizeWhileDragging:!1,resizeContentWhileDragging:!1,noRoomToOpenTip:G.msgNoRoom,resizerTip:G.Resize,sliderTip:G.Slide,sliderCursor:"pointer",slideTrigger_open:"click",slideTrigger_close:"mouseleave",hideTogglerOnSlide:!1,preventQuickSlideClose:!(!f.browser.webkit&&!f.browser.safari),showOverflowOnHover:!1,enableCursorHotkey:!0,customHotkeyModifier:"SHIFT",fxName:"slide",fxSpeed:null,fxSettings:{},fxOpacityFix:!0,
triggerEventsOnLoad:!1,triggerEventsWhileDragging:!0,onshow_start:null,onshow_end:null,onhide_start:null,onhide_end:null,onopen_start:null,onopen_end:null,onclose_start:null,onclose_end:null,onresize_start:null,onresize_end:null,onsizecontent_start:null,onsizecontent_end:null,onswap_start:null,onswap_end:null,ondrag_start:null,ondrag_end:null},north:{paneSelector:".ui-layout-north",size:"auto",resizerCursor:"n-resize",customHotkey:""},south:{paneSelector:".ui-layout-south",size:"auto",resizerCursor:"s-resize",
customHotkey:""},east:{paneSelector:".ui-layout-east",size:200,resizerCursor:"e-resize",customHotkey:""},west:{paneSelector:".ui-layout-west",size:200,resizerCursor:"w-resize",customHotkey:""},center:{paneSelector:".ui-layout-center",minWidth:0,minHeight:0},useStateCookie:!1,cookie:{name:"",autoSave:!0,autoLoad:!0,domain:"",path:"",expires:"",secure:!1,keys:"north.size,south.size,east.size,west.size,north.isClosed,south.isClosed,east.isClosed,west.isClosed,north.isHidden,south.isHidden,east.isHidden,west.isHidden"}},
Ba={slide:{all:{duration:"fast"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},drop:{all:{duration:"slow"},north:{direction:"up"},south:{direction:"down"},east:{direction:"right"},west:{direction:"left"}},scale:{all:{duration:"fast"}}},m={id:"layout"+(new Date).getTime(),initialized:!1,container:{},north:{},south:{},east:{},west:{},center:{},cookie:{}},k={allPanes:"north,south,west,east,center",borderPanes:"north,south,west,east",altSide:{north:"south",
south:"north",east:"west",west:"east"},hidden:{visibility:"hidden"},visible:{visibility:"visible"},zIndex:{pane_normal:1,resizer_normal:2,iframe_mask:2,pane_sliding:100,pane_animate:1E3,resizer_drag:1E4},resizers:{cssReq:{position:"absolute",padding:0,margin:0,fontSize:"1px",textAlign:"left",overflow:"hidden"},cssDemo:{background:"#DDD",border:"none"}},togglers:{cssReq:{position:"absolute",display:"block",padding:0,margin:0,overflow:"hidden",textAlign:"center",fontSize:"1px",cursor:"pointer",zIndex:1},
cssDemo:{background:"#AAA"}},content:{cssReq:{},cssDemo:{overflow:"auto",padding:"10px"},cssDemoPane:{overflow:"hidden",padding:0}},panes:{cssReq:{position:"absolute",margin:0},cssDemo:{padding:"10px",background:"#FFF",border:"1px solid #BBB",overflow:"auto"}},north:{side:"Top",sizeType:"Height",dir:"horz",cssReq:{top:0,bottom:"auto",left:0,right:0,width:"auto"},pins:[]},south:{side:"Bottom",sizeType:"Height",dir:"horz",cssReq:{top:"auto",bottom:0,left:0,right:0,width:"auto"},pins:[]},east:{side:"Right",
sizeType:"Width",dir:"vert",cssReq:{left:"auto",right:0,top:"auto",bottom:"auto",height:"auto"},pins:[]},west:{side:"Left",sizeType:"Width",dir:"vert",cssReq:{left:0,right:"auto",top:"auto",bottom:"auto",height:"auto"},pins:[]},center:{dir:"center",cssReq:{left:"auto",right:"auto",top:"auto",bottom:"auto",height:"auto",width:"auto"}}},H={data:{},set:function(a,b,c){H.clear(a);H.data[a]=setTimeout(b,c)},clear:function(a){var b=H.data;b[a]&&(clearTimeout(b[a]),delete b[a])}},N=function(a){try{return"string"==
typeof a||"object"==typeof a&&null!==a.constructor.toString().match(/string/i)}catch(b){return!1}},C=function(a,b){return Math.max(a,b)},Oa=function(a,b,c){function e(t){var g=k[t];g.doCallback?(d.push(t),t=g.callback.split(",")[1],t!=b&&0<=!f.inArray(t,d)&&e(t)):(g.doCallback=!0,g.callback=a+","+b+","+(c?1:0))}var d=[];f.each(k.borderPanes.split(","),function(a,b){if(k[b].isMoving)return e(b),!1})},Pa=function(a){a=k[a];k.isLayoutBusy=!1;delete a.isMoving;if(a.doCallback&&a.callback){a.doCallback=
!1;var b=a.callback.split(","),c=0<b[2]?!0:!1;"open"==b[0]?X(b[1],c):"close"==b[0]&&R(b[1],c);a.doCallback||(a.callback=null)}},z=function(a,b){if(b){var c;try{if("function"==typeof b)c=b;else if(N(b))if(b.match(/,/)){var e=b.split(",");c=eval(e[0]);if("function"==typeof c&&1<e.length)return c(e[1])}else c=eval(b);else return;if("function"==typeof c)return a&&u[a]?c(a,u[a],f.extend({},m[a]),n[a],n.name):c(Qa,f.extend({},m),n,n.name)}catch(d){}}},Ra=function(a,b){if(!a)return{};a.jquery||(a=f(a));
var c={display:a.css("display"),visibility:a.css("visibility")};return b||"none"==c.display?(a.css({display:"block",visibility:"hidden"}),c):{}},Sa=function(a){if(!m.browser.mozilla){var b=u[a];"IFRAME"==m[a].tagName?b.css(k.hidden).css(k.visible):b.find("IFRAME").css(k.hidden).css(k.visible)}},fa=function(a,b){a.jquery||(a=f(a));var c=Ra(a),e=parseInt(f.curCSS(a[0],b,!0),10)||0;a.css(c);return e},oa=function(a,b){a.jquery&&(a=a[0]);var c="border"+b.substr(0,1).toUpperCase()+b.substr(1);return"none"==
f.curCSS(a,c+"Style",!0)?0:parseInt(f.curCSS(a,c+"Width",!0),10)||0},O=function(a,b){var c=N(a),e=c?u[a]:f(a);isNaN(b)&&(b=c?S(a):e.outerWidth());if(0>=b)return 0;if(!m.browser.boxModel)return b;c=b-oa(e,"Left")-oa(e,"Right")-fa(e,"paddingLeft")-fa(e,"paddingRight");return 0<c?c:0},P=function(a,b){var c=N(a),e=c?u[a]:f(a);isNaN(b)&&(b=c?S(a):e.outerHeight());if(0>=b)return 0;if(!m.browser.boxModel)return b;c=b-oa(e,"Top")-oa(e,"Bottom")-fa(e,"paddingTop")-fa(e,"paddingBottom");return 0<c?c:0},va=
function(a){var b=k[a].dir;a={minWidth:1001-O(a,1E3),minHeight:1001-P(a,1E3)};"horz"==b&&(a.minSize=a.minHeight);"vert"==b&&(a.minSize=a.minWidth);return a},Y=function(a,b,c){c||(c=k[a].dir);N(b)&&b.match(/%/)&&(b=parseInt(b,10)/100);if(0===b)return 0;if(1<=b)return parseInt(b,10);if(0<b){a=n;var e;"horz"==c?e=w.innerHeight-(u.north?a.north.spacing_open:0)-(u.south?a.south.spacing_open:0):"vert"==c&&(e=w.innerWidth-(u.west?a.west.spacing_open:0)-(u.east?a.east.spacing_open:0));return Math.floor(e*
b)}if("center"==a)return 0;e=u[a];c="horz"==c?"height":"width";a=Ra(e);var d=e.css(c);e.css(c,"auto");b="height"==c?e.outerHeight():e.outerWidth();e.css(c,d).css(a);return b},S=function(a,b){var c=u[a],e=n[a],d=m[a],f=b?e.spacing_open:0,e=b?e.spacing_closed:0;return!c||d.isHidden?0:d.isClosed||d.isSliding&&b?e:"horz"==k[a].dir?c.outerHeight()+f:c.outerWidth()+f},T=function(a,b){var c=n[a],e=m[a],d=k[a],f=d.dir;d.side.toLowerCase();d.sizeType.toLowerCase();var d=void 0!=b?b:e.isSliding,g=c.spacing_open,
j=k.altSide[a],l=m[j],h=u[j],s=!h||!1===l.isVisible||l.isSliding?0:"horz"==f?h.outerHeight():h.outerWidth(),j=(!h||l.isHidden?0:n[j][!1!==l.isClosed?"spacing_closed":"spacing_open"])||0,l="horz"==f?w.innerHeight:w.innerWidth,h=va("center"),h="horz"==f?C(n.center.minHeight,h.minHeight):C(n.center.minWidth,h.minWidth),d=l-g-(d?0:Y("center",h,f)+s+j),f=e.minSize=C(Y(a,c.minSize),va(a).minSize),g=c.maxSize?Y(a,c.maxSize):1E5,d=Math.min(g,d),d=e.maxSize=d,e=e.resizerPosition={},g=w.insetTop,s=w.insetLeft,
j=w.innerWidth,l=w.innerHeight,c=c.spacing_open;switch(a){case "north":e.min=g+f;e.max=g+d;break;case "west":e.min=s+f;e.max=s+d;break;case "south":e.min=g+l-d-c;e.max=g+l-f-c;break;case "east":e.min=s+j-d-c,e.max=s+j-f-c}},ga=function(a){var b={},c=b.css={},e={},d,t,g=a.offset();b.offsetLeft=g.left;b.offsetTop=g.top;f.each(["Left","Right","Top","Bottom"],function(f,g){d=c["border"+g]=oa(a,g);t=c["padding"+g]=fa(a,"padding"+g);e[g]=d+t;b["inset"+g]=t});b.offsetWidth=a.innerWidth();b.offsetHeight=
a.innerHeight();b.outerWidth=a.outerWidth();b.outerHeight=a.outerHeight();b.innerWidth=b.outerWidth-e.Left-e.Right;b.innerHeight=b.outerHeight-e.Top-e.Bottom;c.width=a.width();c.height=a.height();return b},Ca=function(a,b){var c={},e=a[0].style,d=b.split(","),f=["Top","Bottom","Left","Right"],g=["Color","Style","Width"],j,l,h,k,m,n;for(k=0;k<d.length;k++)if(j=d[k],j.match(/(border|padding|margin)$/))for(m=0;4>m;m++)if(l=f[m],"border"==j)for(n=0;3>n;n++)h=g[n],c[j+l+h]=e[j+l+h];else c[j+l]=e[j+l];
else c[j]=e[j];return c},Da=function(a,b){var c=f(a),e=c.data("layoutRole"),d=c.data("layoutEdge"),t=n[d][e+"Class"],d="-"+d,g=c.hasClass(t+"-closed")?"-closed":"-open",j="-closed"==g?"-open":"-closed",g=t+"-hover "+(t+d+"-hover ")+(t+g+"-hover ")+(t+d+g+"-hover ");b&&(g+=t+j+"-hover "+(t+d+j+"-hover "));"resizer"==e&&c.hasClass(t+"-sliding")&&(g+=t+"-sliding-hover "+(t+d+"-sliding-hover "));return f.trim(g)},pa=function(a,b){var c=b||this;f(c).addClass(Da(c))},U=function(a,b){var c=b||this;f(c).removeClass(Da(c,
!0))},cb=function(a){f("body").disableSelection();pa(a,this)},Ta=function(a,b){var c=b||this,e=f(c).data("layoutEdge"),d=e+"ResizerLeave";H.clear(d);b?m[e].isResizing||f("body").enableSelection():(U(a,this),H.set(d,function(){Ta(a,c)},200))},db=function(){var a=Number(n.resizeWithWindowDelay)||100;0<a&&(H.clear("winResize"),H.set("winResize",function(){H.clear("winResize");H.clear("winResizeRepeater");wa()},a),H.data.winResizeRepeater||Ua())},Ua=function(){var a=Number(n.resizeWithWindowMaxDelay);
0<a&&H.set("winResizeRepeater",function(){Ua();wa()},a)},Va=function(){var a=n;m.cookie=Aa();a.useStateCookie&&a.cookie.autoSave&&za();z(null,a.onunload)},Wa=function(a){a=n[a].paneSelector;if("#"===a.substr(0,1))return F.find(a).eq(0);var b=F.children(a).eq(0);return b.length?b:F.children("form:first").children(a).eq(0)},Xa=function(a){if(!a||"all"==a)a=k.borderPanes;f.each(a.split(","),function(a,c){var e=u[c];D[c]=!1;J[c]=!1;if(e){var d=n[c],e=m[c],t=d.resizerClass,g=d.togglerClass;k[c].side.toLowerCase();
var j="-"+c,l=D[c]=f("<div></div>"),h=d.closable?J[c]=f("<div></div>"):!1;!e.isVisible&&d.slidable&&l.attr("title",d.sliderTip).css("cursor",d.sliderCursor);l.attr("id","#"==d.paneSelector.substr(0,1)?d.paneSelector.substr(1)+"-resizer":"").data("layoutRole","resizer").data("layoutEdge",c).css(k.resizers.cssReq).css("zIndex",k.zIndex.resizer_normal).css(d.applyDemoStyles?k.resizers.cssDemo:{}).addClass(t+" "+t+j).appendTo(F);h&&(h.attr("id","#"==d.paneSelector.substr(0,1)?d.paneSelector.substr(1)+
"-toggler":"").data("layoutRole","toggler").data("layoutEdge",c).css(k.togglers.cssReq).css(d.applyDemoStyles?k.togglers.cssDemo:{}).addClass(g+" "+g+j).appendTo(l).click(function(a){ia(c);a.stopPropagation()}).hover(pa,U),d.togglerContent_open&&f("<span>"+d.togglerContent_open+"</span>").data("layoutRole","togglerContent").data("layoutEdge",c).addClass("content content-open").css("display","none").appendTo(h).hover(pa,U),d.togglerContent_closed&&f("<span>"+d.togglerContent_closed+"</span>").data("layoutRole",
"togglerContent").data("layoutEdge",c).addClass("content content-closed").css("display","none").appendTo(h).hover(pa,U));var d=c,s="function"==typeof f.fn.draggable,p;if(!d||"all"==d)d=k.borderPanes;f.each(d.split(","),function(a,b){var c=n[b],d=m[b],e=k[b],g="horz"==e.dir?"top":"left",j,l;if(!s||!u[b]||!c.resizable)return c.resizable=!1,!0;var t=D[b],h=c.resizerClass,ea=h+"-drag",q=h+"-"+b+"-drag",r=h+"-dragging",v=h+"-"+b+"-dragging",x=h+"-dragging-limit",y=!1;d.isClosed||t.attr("title",c.resizerTip).css("cursor",
c.resizerCursor);t.hover(cb,Ta);t.draggable({containment:F[0],axis:"horz"==e.dir?"y":"x",delay:0,distance:1,helper:"clone",opacity:c.resizerDragOpacity,addClasses:!1,zIndex:k.zIndex.resizer_drag,start:function(){c=n[b];d=m[b];l=c.resizeWhileDragging;if(!1===z(b,c.ondrag_start))return!1;k.isLayoutBusy=!0;d.isResizing=!0;H.clear(b+"_closeSlider");T(b);j=d.resizerPosition;t.addClass(ea+" "+q);y=!1;p=f(!0===c.maskIframesOnResize?"iframe":c.maskIframesOnResize).filter(":visible");var a,e=0;p.each(function(){a=
"ui-layout-mask-"+ ++e;f(this).data("layoutMaskID",a);f('<div id="'+a+'" class="ui-layout-mask ui-layout-mask-'+b+'"/>').css({background:"#fff",opacity:"0.001",zIndex:k.zIndex.iframe_mask,position:"absolute",width:this.offsetWidth+"px",height:this.offsetHeight+"px"}).css(f(this).position()).appendTo(this.parentNode)});f("body").disableSelection()},drag:function(a,c){y||(c.helper.addClass(r+" "+v).children().css("visibility","hidden"),y=!0,d.isSliding&&u[b].css("zIndex",k.zIndex.pane_sliding));var e=
0;c.position[g]<j.min?(c.position[g]=j.min,e=-1):c.position[g]>j.max&&(c.position[g]=j.max,e=1);e?(c.helper.addClass(x),window.defaultStatus="Panel has reached its "+(0<e&&b.match(/north|west/)||0>e&&b.match(/south|east/)?"maximum":"minimum")+" size"):(c.helper.removeClass(x),window.defaultStatus="");l&&A(a,c,b)},stop:function(a,c){f("body").enableSelection();window.defaultStatus="";t.removeClass(ea+" "+q+" "+x);d.isResizing=!1;k.isLayoutBusy=!1;A(a,c,b,!0)}});var A=function(a,b,d,e){a=b.position;
b=k[d];var g;switch(d){case "north":g=a.top;break;case "west":g=a.left;break;case "south":g=w.offsetHeight-a.top-c.spacing_open;break;case "east":g=w.offsetWidth-a.left-c.spacing_open}if(e){if(f("div.ui-layout-mask").each(function(){this.parentNode.removeChild(this)}),!1===z(d,c.ondrag_end||c.ondrag))return!1}else p.each(function(){f("#"+f(this).data("layoutMaskID")).css(f(this).position()).css({width:this.offsetWidth+"px",height:this.offsetHeight+"px"})});Ea(d,g-w["inset"+b.side])}});e.isVisible?
Fa(c):(Ga(c),qa(c,!0))}});ra("all")},Ya=function(a,b){var c=n[a],e=c.contentSelector,d=u[a],f;e&&(f=Z[a]=c.findNestedContent?d.find(e).eq(0):d.children(e).eq(0));f&&f.length?(f.css(k.content.cssReq),c.applyDemoStyles&&(f.css(k.content.cssDemo),d.css(k.content.cssDemoPane)),m[a].content={},!1!==b&&ja(a)):Z[a]=!1},Ha=function(a,b){var c=n[a],e=m[a],d=u[a],f=D[a];if(d&&!e.isHidden&&!(m.initialized&&!1===z(a,c.onhide_start)))if(e.isSliding=!1,f&&f.hide(),!m.initialized||e.isClosed){if(e.isClosed=!0,e.isHidden=
!0,e.isVisible=!1,d.hide(),aa("horz"==k[a].dir?"all":"center"),m.initialized||c.triggerEventsOnLoad)z(a,c.onhide_end||c.onhide)}else e.isHiding=!0,R(a,!1,b)},xa=function(a,b,c,e){var d=n[a],f=m[a];u[a]&&f.isHidden&&!1!==z(a,d.onshow_start)&&(f.isSliding=!1,f.isShowing=!0,!1===b?R(a,!0):X(a,!1,c,e))},ia=function(a,b){N(a)||(a.stopImmediatePropagation(),a=f(this).data("layoutEdge"));var c=m[N(a)?f.trim(a):void 0==a||null==a?"":a];c.isHidden?xa(a):c.isClosed?X(a,!!b):R(a)},R=function(a,b,c,e){function d(){if(j.isClosed){qa(a,
!0);var b=k.altSide[a];m[b].noRoom&&(T(b),ba(b));if(!e&&(m.initialized||g.triggerEventsOnLoad))l||z(a,g.onclose_end||g.onclose),l&&z(a,g.onshow_end||g.onshow),h&&z(a,g.onhide_end||g.onhide)}Pa(a)}if(m.initialized){var f=u[a],g=n[a],j=m[a];c=!c&&!j.isClosed&&"none"!=g.fxName_close;var l=j.isShowing,h=j.isHiding;delete j.isShowing;delete j.isHiding;if(f&&g.closable&&(b||!j.isClosed||l))if(k.isLayoutBusy)Oa("close",a,b);else if(l||!1!==z(a,g.onclose_start))k[a].isMoving=!0,k.isLayoutBusy=!0,j.isClosed=
!0,j.isVisible=!1,h?j.isHidden=!0:l&&(j.isHidden=!1),j.isSliding?sa(a,!1):aa("horz"==k[a].dir?"all":"center",!1),Ga(a),c?(ya(a,!0),f.hide(g.fxName_close,g.fxSettings_close,g.fxSpeed_close,function(){ya(a,!1);d()})):(f.hide(),d())}else b=m[a],u[a].hide(),b.isClosed=!0,b.isVisible=!1},Ga=function(a){var b=D[a],c=J[a],e=n[a],d=k[a].side.toLowerCase(),t=e.resizerClass,g=e.togglerClass,j="-"+a;b.css(d,w["inset"+k[a].side]).removeClass(t+"-open "+t+j+"-open").removeClass(t+"-sliding "+t+j+"-sliding").addClass(t+
"-closed "+t+j+"-closed").unbind("dblclick."+I);e.resizable&&"function"==typeof f.fn.draggable&&b.draggable("disable").removeClass("ui-state-disabled").css("cursor","default").attr("title","");c&&(c.removeClass(g+"-open "+g+j+"-open").addClass(g+"-closed "+g+j+"-closed").attr("title",e.togglerTip_closed),c.children(".content-open").hide(),c.children(".content-closed").css("display","block"));V(a,!1);m.initialized&&ra("all")},X=function(a,b,c,e){function d(){j.isVisible&&(Sa(a),j.isSliding||aa("vert"==
k[a].dir?"center":"all",!1),Fa(a));Pa(a)}var f=u[a],g=n[a],j=m[a];c=!c&&j.isClosed&&"none"!=g.fxName_open;var l=j.isShowing;delete j.isShowing;if(f&&(g.resizable||g.closable)&&(!j.isVisible||j.isSliding))j.isHidden&&!l?xa(a,!0):k.isLayoutBusy?Oa("open",a,b):!1!==z(a,g.onopen_start)&&(T(a,b),j.minSize>j.maxSize?(V(a,!1),!e&&g.noRoomToOpenTip&&alert(g.noRoomToOpenTip)):(k[a].isMoving=!0,k.isLayoutBusy=!0,b?sa(a,!0):j.isSliding?sa(a,!1):g.slidable&&qa(a,!1),j.noRoom=!1,ba(a),j.isVisible=!0,j.isClosed=
!1,l&&(j.isHidden=!1),c?(ya(a,!0),f.show(g.fxName_open,g.fxSettings_open,g.fxSpeed_open,function(){ya(a,!1);d()})):(f.show(),d())))},Fa=function(a,b){var c=u[a],e=D[a],d=J[a],h=n[a],g=m[a],j=k[a].side.toLowerCase(),l=h.resizerClass,ea=h.togglerClass,s="-"+a;e.css(j,w["inset"+k[a].side]+S(a)).removeClass(l+"-closed "+l+s+"-closed").addClass(l+"-open "+l+s+"-open");g.isSliding?e.addClass(l+"-sliding "+l+s+"-sliding"):e.removeClass(l+"-sliding "+l+s+"-sliding");h.resizerDblClickToggle&&e.bind("dblclick",
ia);U(0,e);h.resizable&&"function"==typeof f.fn.draggable?e.draggable("enable").css("cursor",h.resizerCursor).attr("title",h.resizerTip):g.isSliding||e.css("cursor","default");d&&(d.removeClass(ea+"-closed "+ea+s+"-closed").addClass(ea+"-open "+ea+s+"-open").attr("title",h.togglerTip_open),U(0,d),d.children(".content-closed").hide(),d.children(".content-open").css("display","block"));V(a,!g.isSliding);f.extend(g,ga(c));m.initialized&&(ra("all"),ja(a,!0));if(!b&&(m.initialized||h.triggerEventsOnLoad)&&
c.is(":visible"))z(a,h.onopen_end||h.onopen),g.isShowing&&z(a,h.onshow_end||h.onshow),m.initialized&&(z(a,h.onresize_end||h.onresize),ta(a))},Za=function(a){var b=typeof a,c="string"==b?a:f(this).data("layoutEdge");"object"==b&&a.stopImmediatePropagation();m[c].isClosed?X(c,!0):sa(c,!0)},Ia=function(a){function b(){e.isClosed?sa(c,!1):R(c)}var c=(N(a)?u[a]:f(this)).data("layoutEdge");a=n[c];var e=m[c];!e.isClosed&&!e.isResizing&&("click"==a.slideTrigger_close?b():(!a.preventQuickSlideClose||!k.isLayoutBusy)&&
H.set(c+"_closeSlider",b,300))},ya=function(a,b){var c=u[a];if(b)c.css({zIndex:k.zIndex.pane_animate}),"south"==a?c.css({top:w.insetTop+w.innerHeight-c.outerHeight()}):"east"==a&&c.css({left:w.insetLeft+w.innerWidth-c.outerWidth()});else{c.css({zIndex:m[a].isSliding?k.zIndex.pane_sliding:k.zIndex.pane_normal});"south"==a?c.css({top:"auto"}):"east"==a&&c.css({left:"auto"});var e=n[a];m.browser.msie&&(e.fxOpacityFix&&"slide"!=e.fxName_open&&c.css("filter")&&1==c.css("opacity"))&&c[0].style.removeAttribute("filter")}},
qa=function(a,b){var c=n[a],e=D[a],d=c.slideTrigger_open;e&&c.slidable&&(d.match(/mouseover/)?d=c.slideTrigger_open="mouseenter":d.match(/click|dblclick|mouseenter/)||(d=c.slideTrigger_open="click"),e[b?"bind":"unbind"](d+"."+I,Za).css("cursor",b?c.sliderCursor:"default").attr("title",b?c.sliderTip:""))},sa=function(a,b){function c(b){H.clear(a+"_closeSlider");b.stopPropagation()}var e=n[a],d=k.zIndex,f=e.slideTrigger_close,g=b?"bind":"unbind",j=u[a],l=D[a];m[a].isSliding=b;H.clear(a+"_closeSlider");
b&&qa(a,!1);j.css("zIndex",b?d.pane_sliding:d.pane_normal);l.css("zIndex",b?d.pane_sliding:d.resizer_normal);f.match(/click|mouseleave/)||(f=e.slideTrigger_close="mouseleave");l[g](f,Ia);"mouseleave"==f&&(j[g]("mouseleave."+I,Ia),l[g]("mouseenter."+I,c),j[g]("mouseenter."+I,c));b?"click"==f&&!e.resizable&&(l.css("cursor",b?e.sliderCursor:"default"),l.attr("title",b?e.togglerTip_open:"")):H.clear(a+"_closeSlider")},ba=function(a,b,c,e){b=n[a];var d=m[a],f=k[a],g=u[a],j=D[a],l="vert"==f.dir,h=!1;if("center"==
a||l&&d.noVerticalRoom)(h=d.minHeight<=d.maxHeight&&(l||d.minWidth<=d.maxWidth))&&d.noRoom?(g.show(),j&&j.show(),d.isVisible=!0,d.noRoom=!1,l&&(d.noVerticalRoom=!1),Sa(a)):!h&&!d.noRoom&&(g.hide(),j&&j.hide(),d.isVisible=!1,d.noRoom=!0);"center"!=a&&(d.minSize<=d.maxSize?(d.size>d.maxSize?ka(a,d.maxSize,c,e):d.size<d.minSize?ka(a,d.minSize,c,e):j&&g.is(":visible")&&(c=f.side.toLowerCase(),e=d.size+w["inset"+f.side],fa(j,c)!=e&&j.css(c,e)),d.noRoom&&(d.wasOpen&&b.closable?b.autoReopen?X(a,!1,!0,!0):
d.noRoom=!1:xa(a,d.wasOpen,!0,!0))):d.noRoom||(d.noRoom=!0,d.wasOpen=!d.isClosed&&!d.isSliding,b.closable?R(a,!0,!0):Ha(a,!0)))},Ea=function(a,b,c){var e=n[a],d=e.resizeWhileDragging&&!k.isLayoutBusy;e.autoResize=!1;ka(a,b,c,d)},ka=function(a,b,c,e){var d=n[a],h=m[a],g=u[a],j=D[a],l=k[a].side.toLowerCase(),p="inset"+k[a].side,s=k.isLayoutBusy&&!d.triggerEventsWhileDragging,q;T(a);q=h.size;b=Y(a,b);b=C(b,Y(a,d.minSize));b=Math.min(b,h.maxSize);if(b<h.minSize)ba(a,!1,c);else if(e||b!=q)!c&&(m.initialized&&
h.isVisible)&&z(a,d.onresize_start),g.css(k[a].sizeType.toLowerCase(),C(1,"horz"==k[a].dir?P(a,b):O(a,b))),h.size=b,f.extend(h,ga(g)),j&&g.is(":visible")&&j.css(l,b+w[p]),ja(a),!c&&(!s&&m.initialized&&h.isVisible)&&(z(a,d.onresize_end||d.onresize),ta(a)),c||(h.isSliding||aa("horz"==k[a].dir?"all":"center",s,e),ra("all")),a=k.altSide[a],b<q&&m[a].noRoom&&(T(a),ba(a,!1,c))},aa=function(a,b,c){if(!a||"all"==a)a="east,west,center";f.each(a.split(","),function(a,d){if(u[d]){var h=n[d],g=m[d],j=u[d],l=
!0,k={},l={top:S("north",!0),bottom:S("south",!0),left:S("west",!0),right:S("east",!0),width:0,height:0};l.width=w.innerWidth-l.left-l.right;l.height=w.innerHeight-l.bottom-l.top;l.top+=w.insetTop;l.bottom+=w.insetBottom;l.left+=w.insetLeft;l.right+=w.insetRight;f.extend(g,ga(j));if("center"==d){if(!c&&g.isVisible&&l.width==g.outerWidth&&l.height==g.outerHeight)return!0;f.extend(g,va(d),{maxWidth:l.width,maxHeight:l.height});k=l;k.width=O(d,l.width);k.height=P(d,l.height);l=0<k.width&&0<k.height;
if(!l&&!m.initialized&&0<h.minWidth){var s=h.minWidth-g.outerWidth,q=n.east.minSize||0,p=n.west.minSize||0,r=m.east.size,v=m.west.size,x=r,y=v;0<s&&(m.east.isVisible&&r>q)&&(x=C(r-q,r-s),s-=r-x);0<s&&(m.west.isVisible&&v>p)&&(y=C(v-p,v-s),s-=v-y);if(0==s){r!=q&&ka("east",x,!0);v!=p&&ka("west",y,!0);aa("center",b,c);return}}}else{f.extend(g,ga(j),va(d));if(!c&&!g.noVerticalRoom&&l.height==g.outerHeight)return!0;k.top=l.top;k.bottom=l.bottom;k.height=P(d,l.height);g.maxHeight=C(0,k.height);l=0<g.maxHeight;
l||(g.noVerticalRoom=!0)}l?(!b&&m.initialized&&z(d,h.onresize_start),j.css(k),f.extend(g,ga(j)),g.noRoom&&ba(d),m.initialized&&ja(d)):!g.noRoom&&g.isVisible&&ba(d);"center"==d&&(j=m.browser,j=j.isIE6||j.msie&&!j.boxModel,u.north&&(j||"IFRAME"==m.north.tagName)&&u.north.css("width",O(u.north,w.innerWidth)),u.south&&(j||"IFRAME"==m.south.tagName)&&u.south.css("width",O(u.south,w.innerWidth)));!b&&(m.initialized&&g.isVisible)&&(z(d,h.onresize_end||h.onresize),ta(d))}})},wa=function(){f.extend(m.container,
ga(F));if(w.outerHeight){if(!1===z(null,n.onresizeall_start))return!1;var a,b,c;f.each(["south","north","east","west"],function(a,d){u[d]&&(c=m[d],b=n[d],b.autoResize&&c.size!=b.size?ka(d,b.size,!0,!0):(T(d),ba(d,!1,!0,!0)))});aa("all",!0,!0);ra("all");b=n;f.each(k.allPanes.split(","),function(c,d){if(a=u[d])m[d].isVisible&&z(d,b[d].onresize_end||b[d].onresize),ta(d)});z(null,b.onresizeall_end||b.onresizeall)}},ta=function(a){var b=u[a],c=Z[a];n[a].resizeNestedLayout&&(b.data("layoutContainer")?b.layout().resizeAll():
c&&c.data("layoutContainer")&&c.layout().resizeAll())},ja=function(a,b){if(!a||"all"==a)a=k.allPanes;f.each(a.split(","),function(a,e){function d(a){return C(q.css.paddingBottom,parseInt(a.css("marginBottom"),10)||0)}function h(){var a=n[e].contentIgnoreSelector,a=j.nextAll().not(a||":lt(0)"),b=a.filter(":visible"),c=b.filter(":last");s={top:j[0].offsetTop,height:j.outerHeight(),numFooters:a.length,hiddenFooters:a.length-b.length,spaceBelow:0};s.spaceAbove=s.top;s.bottom=s.top+s.height;s.spaceBelow=
c.length?c[0].offsetTop+c.outerHeight()-s.bottom+d(c):d(j)}var g=u[e],j=Z[e],l=n[e],q=m[e],s=q.content;if(!g||!j||!g.is(":visible"))return!0;if(!1!==z(null,l.onsizecontent_start)){if(!k.isLayoutBusy||void 0==s.top||b||l.resizeContentWhileDragging)h(),0<s.hiddenFooters&&"hidden"==g.css("overflow")&&(g.css("overflow","visible"),h(),g.css("overflow","hidden"));g=q.innerHeight-(s.spaceAbove-q.css.paddingTop)-(s.spaceBelow-q.css.paddingBottom);if(!j.is(":visible")||s.height!=g){var p=j,w=p;N(p)?w=u[p]:
p.jquery||(w=f(p));p=P(w,g);w.css({height:p,visibility:"visible"});0<p&&0<w.innerWidth()?w.data("autoHidden")&&(w.show().data("autoHidden",!1),m.browser.mozilla||w.css(k.hidden).css(k.visible)):!w.data("autoHidden")&&w.hide().data("autoHidden",!0);s.height=g}m.initialized&&(z(e,l.onsizecontent_end||l.onsizecontent),ta(e))}})},ra=function(a){if(!a||"all"==a)a=k.borderPanes;f.each(a.split(","),function(a,c){var e=n[c],d=m[c],h=u[c],g=D[c],j=J[c],l;if(h&&g){var p=k[c].dir,s=d.isClosed?"_closed":"_open",
q=e["spacing"+s],r=e["togglerAlign"+s],s=e["togglerLength"+s],v;if(0==q)g.hide();else{!d.noRoom&&!d.isHidden&&g.show();"horz"==p?(v=h.outerWidth(),d.resizerLength=v,g.css({width:C(1,O(g,v)),height:C(0,P(g,q)),left:fa(h,"left")})):(v=h.outerHeight(),d.resizerLength=v,g.css({height:C(1,P(g,v)),width:C(0,O(g,q)),top:w.insetTop+S("north",!0)}));U(e,g);if(j){if(0==s||d.isSliding&&e.hideTogglerOnSlide){j.hide();return}j.show();if(!(0<s)||"100%"==s||s>v)s=v,r=0;else if(N(r))switch(r){case "top":case "left":r=
0;break;case "bottom":case "right":r=v-s;break;default:r=Math.floor((v-s)/2)}else d=parseInt(r,10),r=0<=r?d:v-s+d;if("horz"==p){var x=O(j,s);j.css({width:C(0,x),height:C(1,P(j,q)),left:r,top:0});j.children(".content").each(function(){l=f(this);l.css("marginLeft",Math.floor((x-l.outerWidth())/2))})}else{var y=P(j,s);j.css({height:C(0,y),width:C(1,O(j,q)),top:r,left:0});j.children(".content").each(function(){l=f(this);l.css("marginTop",Math.floor((y-l.outerHeight())/2))})}U(0,j)}!m.initialized&&e.initHidden&&
(g.hide(),j&&j.hide())}}})},F=f(this).eq(0);if(!F.length)return null;if(F.data("layoutContainer"))return f.extend({},window[F.data("layoutContainer")]);var u={},Z={},D={},J={},w=m.container,I=m.id;var ab=function(a){for(var b in $a)void 0!=a[b]&&(a[$a[b]]=a[b],delete a[b])},A,ca,ua={cookie:{},defaults:{fxSettings:{}},north:{fxSettings:{}},south:{fxSettings:{}},east:{fxSettings:{}},west:{fxSettings:{}},center:{fxSettings:{}}};A=h||{};A.effects||A.cookie||A.defaults||A.north||A.south||A.west||A.east||
A.center?ua=f.extend(!0,ua,A):f.each(A,function(a,b){ca=a.split("__");if(!ca[1]||ua[ca[0]])ua[ca[1]?ca[0]:"defaults"][ca[1]?ca[1]:ca[0]]=b});h=ua;var $a={applyDefaultStyles:"applyDemoStyles"};ab(h.defaults);f.each(k.allPanes.split(","),function(a,b){ab(h[b])});h.effects&&(f.extend(Ba,h.effects),delete h.effects);f.extend(n.cookie,h.cookie);f.each("name zIndex scrollToBookmarkOnLoad resizeWithWindow resizeWithWindowDelay resizeWithWindowMaxDelay onresizeall onresizeall_start onresizeall_end onload onunload autoBindCustomButtons useStateCookie".split(" "),
function(a,b){void 0!==h[b]?n[b]=h[b]:void 0!==h.defaults[b]&&(n[b]=h.defaults[b],delete h.defaults[b])});f.each(["paneSelector","resizerCursor","customHotkey"],function(a,b){delete h.defaults[b]});f.extend(!0,n.defaults,h.defaults);k.center=f.extend(!0,{},k.panes,k.center);A=n.zIndex;if(0===A||0<A)k.zIndex.pane_normal=A,k.zIndex.resizer_normal=A+1,k.zIndex.iframe_mask=A+1;f.extend(n.center,h.center);var eb=f.extend(!0,{},n.defaults,h.defaults,n.center);f.each("paneClass contentSelector applyDemoStyles triggerEventsOnLoad showOverflowOnHover onresize onresize_start onresize_end resizeNestedLayout resizeContentWhileDragging onsizecontent onsizecontent_start onsizecontent_end".split(" "),
function(a,b){n.center[b]=eb[b]});var B,la=n.defaults;f.each(k.borderPanes.split(","),function(a,b){k[b]=f.extend(!0,{},k.panes,k[b]);B=n[b]=f.extend(!0,{},n.defaults,n[b],h.defaults,h[b]);B.paneClass||(B.paneClass="ui-layout-pane");B.resizerClass||(B.resizerClass="ui-layout-resizer");B.togglerClass||(B.togglerClass="ui-layout-toggler");f.each(["_open","_close",""],function(a,e){var d="fxName"+e,k="fxSpeed"+e,g="fxSettings"+e;B[d]=h[b][d]||h[b].fxName||h.defaults[d]||h.defaults.fxName||B[d]||B.fxName||
la[d]||la.fxName||"none";var j=B[d];if("none"==j||!f.effects||!f.effects[j]||!Ba[j]&&!B[g]&&!B.fxSettings)j=B[d]="none";j=Ba[j]||{};d=j.all||{};j=j[b]||{};B[g]=f.extend({},d,j,la.fxSettings||{},la[g]||{},B.fxSettings,B[g],h.defaults.fxSettings,h.defaults[g]||{},h[b].fxSettings,h[b][g]||{});B[k]=h[b][k]||h[b].fxSpeed||h.defaults[k]||h.defaults.fxSpeed||B[k]||B[g].duration||B.fxSpeed||B.fxSettings.duration||la.fxSpeed||la.fxSettings.duration||j.duration||d.duration||"normal"})});A=n;if(!1!==z(null,
A.onload))if(Wa("center").length){A.useStateCookie&&A.cookie.autoLoad&&Ma();m.browser={mozilla:f.browser.mozilla,webkit:f.browser.webkit||f.browser.safari,msie:f.browser.msie,isIE6:f.browser.msie&&6==f.browser.version,boxModel:f.support.boxModel};var E=F,ha=w.tagName=f.prop?E.prop("tagName"):E.attr("tagName"),bb="BODY"==ha,ma={};w.selector=E.selector.split(".slice")[0];w.ref=ha+"/"+w.selector;E.data("layoutContainer",I).data("layoutName",n.name);E.data("layoutCSS")||(bb?(ma=f.extend(Ca(E,"position,margin,padding,border"),
{height:E.css("height"),overflow:E.css("overflow"),overflowX:E.css("overflowX"),overflowY:E.css("overflowY")}),ha=f("html"),ha.data("layoutCSS",{height:"auto",overflow:ha.css("overflow"),overflowX:ha.css("overflowX"),overflowY:ha.css("overflowY")})):ma=Ca(E,"position,margin,padding,border,top,bottom,left,right,width,height,overflow,overflowX,overflowY"),E.data("layoutCSS",ma));try{if(bb)f("html").css({height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden"}),f("body").css({position:"relative",
height:"100%",overflow:"hidden",overflowX:"hidden",overflowY:"hidden",margin:0,padding:0,border:"none"});else{var ma={overflow:"hidden"},na=E.css("position");E.css("height");if(!E.data("layoutRole")&&(!na||!na.match(/fixed|absolute|relative/)))ma.position="relative";E.css(ma);E.is(":visible")&&2>E.innerHeight()&&alert(G.errContainerHeight.replace(/CONTAINER/,w.ref))}}catch(fb){}f.extend(m.container,ga(E));f.each(k.allPanes.split(","),function(a,b){var c=n[b],e=m[b],d=k[b],h=d.dir,g="center"==b,j=
{},l,p,s;Z[b]=!1;l=u[b]=Wa(b);if(!l.length)return u[b]=!1,!0;l.data("layoutCSS")||l.data("layoutCSS",Ca(l,"position,top,left,bottom,right,width,height,overflow,zIndex,display,backgroundColor,padding,margin,border"));l.data("layoutName",n.name).data("layoutRole","pane").data("layoutEdge",b).css(d.cssReq).css("zIndex",k.zIndex.pane_normal).css(c.applyDemoStyles?d.cssDemo:{}).addClass(c.paneClass+" "+c.paneClass+"-"+b).bind("mouseenter."+I,pa).bind("mouseleave."+I,U);Ya(b,!1);g||(p=e.size=Y(b,c.size),
d=Y(b,c.minSize)||1,s=Y(b,c.maxSize)||1E5,0<p&&(p=C(Math.min(p,s),d)));e.tagName=f.prop?l.prop("tagName"):l.attr("tagName");e.edge=b;e.noRoom=!1;e.isVisible=!0;g||(e.isClosed=!1,e.isSliding=!1,e.isResizing=!1,e.isHidden=!1);switch(b){case "north":j.top=w.insetTop;j.left=w.insetLeft;j.right=w.insetRight;break;case "south":j.bottom=w.insetBottom;j.left=w.insetLeft;j.right=w.insetRight;break;case "west":j.left=w.insetLeft;break;case "east":j.right=w.insetRight}"horz"==h?j.height=C(1,P(b,p)):"vert"==
h&&(j.width=C(1,O(b,p)));l.css(j);"horz"!=h&&aa(b,!0);l.css({visibility:"visible",display:"block"});c.initClosed&&c.closable?R(b,!0,!0):(c.initHidden||c.initClosed)&&Ha(b);c.showOverflowOnHover&&l.hover(q,r)});Xa();f.each(k.borderPanes.split(","),function(a,b){u[b]&&m[b].isVisible&&(T(b),ba(b))});aa("center");f.each(k.allPanes.split(","),function(a,b){var c=n[b];u[b]&&(c.triggerEventsOnLoad&&m[b].isVisible)&&z(b,c.onresize_end||c.onresize)});2>F.innerHeight()&&alert(G.errContainerHeight.replace(/CONTAINER/,
w.ref));ja();A.scrollToBookmarkOnLoad&&(na=self.location,na.hash&&na.replace(na.hash));if(A.autoBindCustomButtons){var Ja;f.each("toggle open close pin toggle-slide open-slide".split(" "),function(a,b){f.each(k.borderPanes.split(","),function(a,e){f(".ui-layout-button-"+b+"-"+e).each(function(){Ja=f(this).data("layoutName")||f(this).attr("layoutName");(void 0==Ja||Ja==n.name)&&M(this,b,e)})})})}f.each(k.borderPanes.split(","),function(a,b){var c=n[b];if(c.enableCursorHotkey||c.customHotkey)return f(document).bind("keydown."+
I,p),!1});A.resizeWithWindow&&!F.data("layoutRole")&&f(window).bind("resize."+I,db);f(window).bind("unload."+I,Va);m.initialized=!0}else alert(G.errCenterPaneMissing);var Qa={options:n,state:m,container:F,panes:u,contents:Z,resizers:D,togglers:J,toggle:ia,hide:Ha,show:xa,open:X,close:R,slideOpen:Za,slideClose:Ia,slideToggle:function(a){ia(a,!0)},initContent:Ya,sizeContent:ja,sizePane:Ea,swapPanes:function(a,b){function c(a){var b=u[a],c=Z[a];return!b?!1:{pane:a,P:b?b[0]:!1,C:c?c[0]:!1,state:f.extend({},
m[a]),options:f.extend({},n[a])}}function e(a,b){if(a){var c=a.P,d=a.C,e=a.pane,h=k[b],p=h.side.toLowerCase(),q="inset"+h.side,t=f.extend({},m[b]),r=n[b],v={resizerCursor:r.resizerCursor};f.each(["fxName","fxSpeed","fxSettings"],function(a,b){v[b]=r[b];v[b+"_open"]=r[b+"_open"];v[b+"_close"]=r[b+"_close"]});u[b]=f(c).data("layoutEdge",b).css(k.hidden).css(h.cssReq);Z[b]=d?f(d):!1;n[b]=f.extend({},a.options,v);m[b]=f.extend({},a.state);c.className=c.className.replace(RegExp(r.paneClass+"-"+e,"g"),
r.paneClass+"-"+b);Xa(b);h.dir!=k[e].dir?(c=g[b]||0,T(b),c=C(c,m[b].minSize),Ea(b,c,!0)):D[b].css(p,w[q]+(m[b].isVisible?S(b):0));a.state.isVisible&&!t.isVisible?Fa(b,!0):(Ga(b),qa(b,!0));a=null}}m[a].edge=b;m[b].edge=a;var d=!1;!1===z(a,n[a].onswap_start)&&(d=!0);!d&&!1===z(b,n[b].onswap_start)&&(d=!0);if(d)m[a].edge=a,m[b].edge=b;else{var d=c(a),h=c(b),g={};g[a]=d?d.state.size:0;g[b]=h?h.state.size:0;u[a]=!1;u[b]=!1;m[a]={};m[b]={};J[a]&&J[a].remove();J[b]&&J[b].remove();D[a]&&D[a].remove();D[b]&&
D[b].remove();D[a]=D[b]=J[a]=J[b]=!1;e(d,b);e(h,a);d=h=g=null;u[a]&&u[a].css(k.visible);u[b]&&u[b].css(k.visible);wa();z(a,n[a].onswap_end||n[a].onswap);z(b,n[b].onswap_end||n[b].onswap)}},resizeAll:wa,destroy:function(){f(window).unbind("."+I);f(document).unbind("."+I);window[I]=null;var a="BODY"==w.tagName,b,c,e,d;f.each(k.allPanes.split(","),function(a,g){b=u[g];if(!b)return!0;"center"!=g&&(J[g]&&J[g].remove(),D[g].remove());c=n[g].paneClass;e=c+"-"+g;d=[c,c+"-open",c+"-closed",c+"-sliding",e,
e+"-open",e+"-closed",e+"-sliding"];f.merge(d,Da(b,!0));b.removeClass(d.join(" ")).removeData("layoutRole").removeData("layoutEdge").unbind("."+I).unbind("mouseenter").unbind("mouseleave");b.data("layoutContainer")||b.css(b.data("layoutCSS"))});F.removeData("layoutContainer");F.data("layoutEdge")||F.css(F.data("layoutCSS"));a&&f("html").css(f("html").data("layoutCSS"));Va();(a=n.name)&&window[a]&&(window[a]=null)},setSizeLimits:T,bindButton:M,addToggleBtn:x,addOpenBtn:y,addCloseBtn:L,addPinBtn:Q,
allowOverflow:q,resetOverflow:r,encodeJSON:La,decodeJSON:Ka,getState:Aa,getCookie:da,saveCookie:za,deleteCookie:function(){za("",{expires:-1})},loadCookie:Ma,loadState:Na,cssWidth:O,cssHeight:P};return window[I]=Qa}})(jQuery);
var layoutState={options:{layoutName:"mywebsql",keys:"north__size,south__size,east__size,west__size,north__isClosed,south__isClosed,east__isClosed,west__isClosed,north__isHidden,south__isHidden,east__isHidden,west__isHidden",domain:"",path:"",expires:"60",secure:!1},data:{},clear:function(f){this.save(f,"layout",{expires:-1})},save:function(f,v,h){h=jQuery.extend({},this.options,h||{});var p=window[f||h.layoutName];v||(v=h.keys);"string"==typeof v&&(v=v.split(","));if(!p||!p.state||!v.length)return!1;
var q="number"==typeof h.expires,r=new Date,K="",M=!1;if(q||h.expires.toUTCString)q?0>=h.expires?(r.setYear(1970),M=!0):r.setTime(r.getTime()+864E5*h.expires):r=h.expires,K+=";expires="+r.toUTCString();h.path&&(K+=";path="+h.path);h.domain&&(K+=";domain="+h.domain);h.secure&&(K+=";secure");if(M)this.data={},$.cookies.set(f||h.layoutName,K,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME});else{for(var p=p.state,q={},r={isClosed:"initClosed",isHidden:"initHidden"},M=0<v[0].indexOf("__")?"__":".",x,
y,L,Q=0;Q<v.length;Q++)x=v[Q].split(M),y=x[0],x=x[1],0>"north,south,east,west,center".indexOf(y)||(L="isClosed"==x?p[y][x]||p[y].isSliding:p[y][x],void 0!=L&&("."==M?(q[y]||(q[y]={}),q[y][r[x]?r[x]:x]=L):q[y+M+(r[x]?r[x]:x)]=L));this.data=q;$.cookies.set(f||h.layoutName,encodeURIComponent(JSON.stringify(this.data))+K,{path:EXTERNAL_PATH,hoursToLive:COOKIE_LIFETIME})}return this.data},load:function(f){f||(f=this.options.layoutName);if(!f)return{};var v={};(ck=$.cookies.get(f))&&(v=JSON.parse(decodeURIComponent(ck)));
return this.data=v}};
